# Generated by Django 2.1.7 on 2019-03-19 10:50

from django.db import migrations, models


def update_rating(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    Vote = apps.get_model('blog', 'Vote')
    for post in Post.objects.all():
        upvotes = Vote.objects.filter(post=post, up=True).count()
        downvotes = Vote.objects.filter(post=post, up=False).count()
        if upvotes or downvotes:
            post.upvotes = upvotes
            post.downvotes = downvotes
            post.rating = upvotes - downvotes
            post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created'], name='blog_post_created_594d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['rating'], name='blog_post_rating_a1c6bb_idx'),
        ),
        migrations.RunPython(update_rating),
    ]
